name: "Template to Readme"

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 15,30 * *"

jobs:
  generate-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          fetch-depth: 0
      - name: Update TEMPLATE.md
        run: |
          bun install
          bun start
      - name: Generate README.md
        uses: teoxoy/profile-readme-stats@v2
        with:
          token: ${{ secrets.USER_TOKEN }}
      - name: Update README.md
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
          git config user.name gh-actions[bot]
          git config user.email 89240639+gh-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Update README from TEMPLATE"
          git push
          fi
