name: Update

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: 1️⃣ Transpile TypeScript
        run: |
          cd ${GITHUB_WORKSPACE}
          npm install -g yarn
          yarn install
          yarn build
      - name: 2️⃣ Run Transpiled Code
        run: |
          yarn start
      - name: 3️⃣ Version Control
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "Automatic weekly update"
          git push -u origin main
